### ISSUE TITLE
Question: how to attach callback after scan

### ISSUE THREAD

**Issue by js2me** [euberdeveloper/dree#2]
Hi!
I have part of code
```
dree.scan(
  path.resolve(__dirname, "./test"),
  {
    extensions: ["html"],
    depth: 999999
  },
  file => attachFile(file)
);
```
And currently I needed to create a callback when the all files has been scaned.
It is possible?

I think it should be like
```
dree.scan(
  path.resolve(__dirname, "./test"),
  {
    extensions: ["html"],
    depth: 999999,
    onEnd: () => {
       console.log('all html files has been scaned! Congrats!')
    }
  },
  file => attachFile(file)
);
```

**Comment by euberdeveloper** [comment]
Hi js2me!

The **fileCallback** callback is called soon after a File is added to the directory tree. This is useful because it is executed when the scan is not finished yet and because it provides you the object and stat representing your file.

In this case, if I understood well, you simply need to do something, such as logging the fact that all files are scanned, **after** that **all** files - so everything - is scanned. Since the function **scan** is **synchronous**, you simply should log it or do whatever else you want after the function is executed. 

Such as:

```js
const tree = dree.scan(
  path.resolve(__dirname, './test'),
  {
    extensions: [ 'html' ],
    depth: 999999
  },
  file => attachFile(file)
);
console.log('all html files has been scanned! Congrats!');
```
__NB:__ I see you are using the property **depth** setted to a large number. I don't know why you are using it, it could be good, for instance if your folder is very very deep and you want to stop at a quite big depth. However, if you want to scan all the directory, you can omit the depth propery.

__NB:__ I am quite busy now, but I am planning to extend the module to support async methods too.

I hope it did answer

**Comment by js2me** [comment]
@euberdeveloper Hi, thanks for your answer and for your big explanation.
Just my problem was in using async reading files in the `fileCallback` and this is nothing related to this library. And because of this I'll close issue.
Thanks for your library, like it!
