### ISSUE TITLE
Feature Request: Sort directories before files

### ISSUE THREAD

**Issue by AlexanderZeilmann** [euberdeveloper/dree#38]
I would like to sort the output such that directories are sorted before files. So I want to have first all directories in alphabetical order, then all files in alphabetical order.

Currently, it seems that the [`sorted` function](https://dree.euber.dev/types/SortDiscriminator.html) receives only the file/directory name, but not any additional information like the path or whether it is a directory. Is there something I am missing or is this currently not possible?

**Comment by AlexanderZeilmann** [comment]
Now that I think more about it more generally, I think it would be nice to also have the `node` and `stat` arguments from the callbacks in the sorting function. That way one could also sort the files and directories by e.g. size or creation date.

**Comment by euberdeveloper** [comment]
Hello, sorry for the late response, I will handle this issue today

**Comment by euberdeveloper** [comment]
The problem seems to be [here](https://github.com/euberdeveloper/dree/blob/57c5e3f91bfdc4da191624223c6514bd9a1c1fd1/source/lib/index.ts#L489). The names of the subfolders / subfiles are taken, then the sort is executed and only after that the children are handled with the recursive function. 

This means also that the sort function defines the order in which the file/dir callbacks are executed. Changing this would be a breaking change, so I will think to an alternative

**Comment by euberdeveloper** [comment]
The feature has been added by the release [4.8.0](https://github.com/euberdeveloper/dree/releases/tag/4.8.0)

A new option `postSorted` has been added, this way it is possible to sort after the child nodes are handled and handle the sorting with the nodes themselves. The node can contian the stats info in itself. 

If you want the same behaviour also for the funciton `parse`, it is suggested to use `scan` and pass the result to `parseAsync` instead.
